substitutions:
  name: boneio-c-07
  friendly_name: 'BoneIO Rolety'

esphome:
  name: '${name}'
  friendly_name: '${friendly_name}'
  name_add_mac_suffix: true
  project:
    name: boneio.32x10-cover
    version: '0.7'

esp32:
  board: nodemcu-32s

ethernet:
  id: eth
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

dashboard_import:
  package_import_url: github://boneIO-eu/amizera/boneio-cover_plusDoor_v0_7.yaml@v1.0.0
  import_full_config: true

packages:
  internals_packages:
    url: https://github.com/amizera/esphome
    #ref: v1.0.4
    files: [
        'devices/buzzer.yaml',
        'devices_v0_7/display.yaml',
        'devices_v0_7/i2c.yaml',
        'devices_v0_7/ina219.yaml',
        'devices_v0_7/lm75b.yaml',
        'devices_v0_7/pcf.yaml',
        'boards/16_cover_pcf_plusDoor.yaml',
        # 'devices_v0_7/one_wire.yaml',
        # 'devices_v0_7/uart.yaml',
      ]

logger:
api:
ota:
  password: boneio

web_server:
  port: 80
  local: true

time:
  - platform: homeassistant
    timezone: Europe/Warsaw
    id: homeassistant_time

cover:
  - platform: time_based
    name: 'Cover 01'
    id: cover_01
    open_action:
      - switch.turn_off: cover_close_01_out02
      - switch.turn_on: cover_open_01_out01
    open_duration: 18s
    close_action:
      - switch.turn_off: cover_open_01_out01
      - switch.turn_on: cover_close_01_out02
    close_duration: 17s
    stop_action:
      - switch.turn_off: cover_open_01_out01
      - switch.turn_off: cover_close_01_out02

  - platform: time_based
    name: 'Łazienka'
    id: cover_02
    open_action:
      - switch.turn_off: cover_close_02_out04
      - switch.turn_on: cover_open_02_out03
    open_duration: 18s
    close_action:
      - switch.turn_off: cover_open_02_out03
      - switch.turn_on: cover_close_02_out04
    close_duration: 17s
    stop_action:
      - switch.turn_off: cover_open_02_out03
      - switch.turn_off: cover_close_02_out04

  - platform: time_based
    name: 'Kuchnia drzwi'
    id: cover_03
    open_action:
      - switch.turn_off: cover_close_03_out06
      - switch.turn_on: cover_open_03_out05
    open_duration: 33s
    close_action:
      - switch.turn_off: cover_open_03_out05
      - switch.turn_on: cover_close_03_out06
    close_duration: 33s
    stop_action:
      - switch.turn_off: cover_open_03_out05
      - switch.turn_off: cover_close_03_out06

  - platform: time_based
    name: 'Gabinet'
    id: cover_04
    open_action:
      - switch.turn_off: cover_close_04_out08
      - switch.turn_on: cover_open_04_out07
    open_duration: 18s
    close_action:
      - switch.turn_off: cover_open_04_out07
      - switch.turn_on: cover_close_04_out08
    close_duration: 17s
    stop_action:
      - switch.turn_off: cover_open_04_out07
      - switch.turn_off: cover_close_04_out08

  - platform: time_based
    name: 'Kuchnia okno'
    id: cover_05
    open_action:
      - switch.turn_off: cover_close_05_out10
      - switch.turn_on: cover_open_05_out09
    open_duration: 18s
    close_action:
      - switch.turn_off: cover_open_05_out09
      - switch.turn_on: cover_close_05_out10
    close_duration: 17s
    stop_action:
      - switch.turn_off: cover_open_05_out09
      - switch.turn_off: cover_close_05_out10

  - platform: time_based
    name: 'Pralnia'
    id: cover_06
    open_action:
      - switch.turn_off: cover_close_06_out12
      - switch.turn_on: cover_open_06_out11
    open_duration: 18s
    close_action:
      - switch.turn_off: cover_open_06_out11
      - switch.turn_on: cover_close_06_out12
    close_duration: 17s
    stop_action:
      - switch.turn_off: cover_open_06_out11
      - switch.turn_off: cover_close_06_out12

  - platform: time_based
    name: 'Salon FIX'
    id: cover_07
    open_action:
      - switch.turn_off: cover_close_07_out14
      - switch.turn_on: cover_open_07_out13
    open_duration: 27s
    close_action:
      - switch.turn_off: cover_open_07_out13
      - switch.turn_on: cover_close_07_out14
    close_duration: 21s
    stop_action:
      - switch.turn_off: cover_open_07_out13
      - switch.turn_off: cover_close_07_out14

  - platform: time_based
    name: 'Salon drzwi'
    id: cover_08
    open_action:
      - switch.turn_off: cover_close_08_out16
      - switch.turn_on: cover_open_08_out15
    open_duration: 27s
    close_action:
      - switch.turn_off: cover_open_08_out15
      - switch.turn_on: cover_close_08_out16
    close_duration: 24s
    stop_action:
      - switch.turn_off: cover_open_08_out15
      - switch.turn_off: cover_close_08_out16

  - platform: time_based
    name: 'Salon HS FIX'
    id: cover_09
    open_action:
      - switch.turn_off: cover_close_09_out18
      - switch.turn_on: cover_open_09_out17
    open_duration: 27s
    close_action:
      - switch.turn_off: cover_open_09_out17
      - switch.turn_on: cover_close_09_out18
    close_duration: 24s
    stop_action:
      - switch.turn_off: cover_open_09_out17
      - switch.turn_off: cover_close_09_out18

  - platform: time_based
    name: 'Salon HS'
    id: cover_10
    open_action:
      - switch.turn_off: cover_close_10_out20
      - switch.turn_on: cover_open_10_out19
    open_duration: 27s
    close_action:
      - switch.turn_off: cover_open_10_out19
      - switch.turn_on: cover_close_10_out20
    close_duration: 24s
    stop_action:
      - switch.turn_off: cover_open_10_out19
      - switch.turn_off: cover_close_10_out20

  - platform: time_based
    name: 'Cover 11'
    id: cover_11
    open_action:
      - switch.turn_off: cover_close_11_out22
      - switch.turn_on: cover_open_11_out21
    open_duration: 18s
    close_action:
      - switch.turn_off: cover_open_11_out21
      - switch.turn_on: cover_close_11_out22
    close_duration: 17s
    stop_action:
      - switch.turn_off: cover_open_11_out21
      - switch.turn_off: cover_close_11_out22

  - platform: time_based
    name: 'Cover 12'
    id: cover_12
    open_action:
      - switch.turn_off: cover_close_12_out24
      - switch.turn_on: cover_open_12_out23
    open_duration: 18s
    close_action:
      - switch.turn_off: cover_open_12_out23
      - switch.turn_on: cover_close_12_out24
    close_duration: 17s
    stop_action:
      - switch.turn_off: cover_open_12_out23
      - switch.turn_off: cover_close_12_out24

  - platform: time_based
    name: 'Cover 13'
    id: cover_13
    open_action:
      - switch.turn_off: cover_close_13_out26
      - switch.turn_on: cover_open_13_out25
    open_duration: 18s
    close_action:
      - switch.turn_off: cover_open_13_out25
      - switch.turn_on: cover_close_13_out26
    close_duration: 17s
    stop_action:
      - switch.turn_off: cover_open_13_out25
      - switch.turn_off: cover_close_13_out26

  - platform: time_based
    name: 'Cover 14'
    id: cover_14
    open_action:
      - switch.turn_off: cover_close_14_out28
      - switch.turn_on: cover_open_14_out27
    open_duration: 18s
    close_action:
      - switch.turn_off: cover_open_14_out27
      - switch.turn_on: cover_close_14_out28
    close_duration: 17s
    stop_action:
      - switch.turn_off: cover_open_14_out27
      - switch.turn_off: cover_close_14_out28

  - platform: time_based
    name: 'Cover 15'
    id: cover_15
    open_action:
      - switch.turn_off: cover_close_15_out30
      - switch.turn_on: cover_open_15_out29
    open_duration: 18s
    close_action:
      - switch.turn_off: cover_open_15_out29
      - switch.turn_on: cover_close_15_out30
    close_duration: 17s
    stop_action:
      - switch.turn_off: cover_open_15_out29
      - switch.turn_off: cover_close_15_out30

lock:
  - platform: output
    name: "Drzwi"
    id: door_01
    output: lock_01
    on_unlock:
      then:
        - delay: 2000ms
        - lock.lock: door_01

binary_sensor:
  - platform: gpio
    name: 'IN_01'
    id: in_01
    pin:
      pcf8574: pcf_inputs_1to14
      number: 0
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.open: cover_01
    on_release:
      then:
        - cover.stop: cover_01

  - platform: gpio
    name: 'IN_02'
    id: in_02
    pin:
      pcf8574: pcf_inputs_1to14
      number: 1
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.close: cover_01
    on_release:
      then:
        - cover.stop: cover_01

  - platform: gpio
    name: 'IN_03'
    id: in_03
    pin:
      pcf8574: pcf_inputs_1to14
      number: 2
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.open: cover_02
    on_release:
      then:
        - cover.stop: cover_02

  - platform: gpio
    name: 'IN_04'
    id: in_04
    pin:
      pcf8574: pcf_inputs_1to14
      number: 3
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.close: cover_02
    on_release:
      then:
        - cover.stop: cover_02

  - platform: gpio
    name: 'IN_05'
    id: in_05
    pin:
      pcf8574: pcf_inputs_1to14
      number: 4
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.open: cover_03
    on_release:
      then:
        - cover.stop: cover_03

  - platform: gpio
    name: 'IN_06'
    id: in_06
    pin:
      pcf8574: pcf_inputs_1to14
      number: 5
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.close: cover_03
    on_release:
      then:
        - cover.stop: cover_03

  - platform: gpio
    name: 'IN_07'
    id: in_07
    pin:
      pcf8574: pcf_inputs_1to14
      number: 6
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.open: cover_04
    on_release:
      then:
        - cover.stop: cover_04

  - platform: gpio
    name: 'IN_08'
    id: in_08
    pin:
      pcf8574: pcf_inputs_1to14
      number: 8
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.close: cover_04
    on_release:
      then:
        - cover.stop: cover_04

  - platform: gpio
    name: 'IN_09'
    id: in_09
    pin:
      pcf8574: pcf_inputs_1to14
      number: 9
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.open: cover_05
    on_release:
      then:
        - cover.stop: cover_05

  - platform: gpio
    name: 'IN_10'
    id: in_10
    pin:
      pcf8574: pcf_inputs_1to14
      number: 10
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.close: cover_05
    on_release:
      then:
        - cover.stop: cover_05

  - platform: gpio
    name: 'IN_11'
    id: in_11
    pin:
      pcf8574: pcf_inputs_1to14
      number: 11
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.open: cover_06
    on_release:
      then:
        - cover.stop: cover_06

  - platform: gpio
    name: 'IN_12'
    id: in_12
    pin:
      pcf8574: pcf_inputs_1to14
      number: 12
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.close: cover_06
    on_release:
      then:
        - cover.stop: cover_06

  - platform: gpio
    name: 'IN_13'
    id: in_13
    pin:
      pcf8574: pcf_inputs_1to14
      number: 13
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.open: cover_07
    on_release:
      then:
        - cover.stop: cover_07

  - platform: gpio
    name: 'IN_14'
    id: in_14
    pin:
      pcf8574: pcf_inputs_1to14
      number: 14
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.close: cover_07
    on_release:
      then:
        - cover.stop: cover_07

  - platform: gpio
    name: 'IN_15'
    id: in_15
    pin:
      pcf8574: pcf_inputs_15to28
      number: 6
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.open: cover_08
    on_release:
      then:
        - cover.stop: cover_08

  - platform: gpio
    name: 'IN_16'
    id: in_16
    pin:
      pcf8574: pcf_inputs_15to28
      number: 5
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.close: cover_08
    on_release:
      then:
        - cover.stop: cover_08

  - platform: gpio
    name: 'IN_17'
    id: in_17
    pin:
      pcf8574: pcf_inputs_15to28
      number: 4
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.open: cover_09
    on_release:
      then:
        - cover.stop: cover_09

  - platform: gpio
    name: 'IN_18'
    id: in_18
    pin:
      pcf8574: pcf_inputs_15to28
      number: 3
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.close: cover_09
    on_release:
      then:
        - cover.stop: cover_09

  - platform: gpio
    name: 'IN_19'
    id: in_19
    pin:
      pcf8574: pcf_inputs_15to28
      number: 2
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.open: cover_10
    on_release:
      then:
        - cover.stop: cover_10

  - platform: gpio
    name: 'IN_20'
    id: in_20
    pin:
      pcf8574: pcf_inputs_15to28
      number: 1
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.close: cover_10
    on_release:
      then:
        - cover.stop: cover_10

  - platform: gpio
    name: 'IN_21'
    id: in_21
    pin:
      pcf8574: pcf_inputs_15to28
      number: 0
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.open: cover_11
    on_release:
      then:
        - cover.stop: cover_11

  - platform: gpio
    name: 'IN_22'
    id: in_22
    pin:
      pcf8574: pcf_inputs_15to28
      number: 8
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.close: cover_11
    on_release:
      then:
        - cover.stop: cover_11

  - platform: gpio
    name: 'IN_23'
    id: in_23
    pin:
      pcf8574: pcf_inputs_15to28
      number: 9
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.open: cover_12
    on_release:
      then:
        - cover.stop: cover_12

  - platform: gpio
    name: 'Salon_HS'
    id: in_24
    pin:
      pcf8574: pcf_inputs_15to28
      number: 10
      mode:
        input: true
    #   inverted: true
    # on_press:
    #   then:
    #     - cover.close: cover_12
    # on_release:
    #   then:
    #     - cover.stop: cover_12

  - platform: gpio
    name: 'Pralnia_OS'
    id: in_25
    pin:
      pcf8574: pcf_inputs_15to28
      number: 11
      mode:
        input: true
    # inverted: true
    # on_press:
    #   then:
    #     - cover.open: cover_13
    # on_release:
    #   then:
    #     - cover.stop: cover_13

  - platform: gpio
    name: 'Pralnia_OU'
    id: in_26
    pin:
      pcf8574: pcf_inputs_15to28
      number: 12
      mode:
        input: true
    #   inverted: true
    # on_press:
    #   then:
    #     - cover.close: cover_13
    # on_release:
    #   then:
    #     - cover.stop: cover_13

  - platform: gpio
    name: 'SALON_DS'
    id: in_27
    pin:
      pcf8574: pcf_inputs_15to28
      number: 13
      mode:
        input: true
    #   inverted: true
    # on_press:
    #   then:
    #     - cover.open: cover_14
    # on_release:
    #   then:
    #     - cover.stop: cover_14

  - platform: gpio
    name: 'SALON_DU'
    id: in_28
    pin:
      pcf8574: pcf_inputs_15to28
      number: 14
      mode:
        input: true
    #   inverted: true
    # on_press:
    #   then:
    #     - cover.close: cover_14
    # on_release:
    #   then:
    #     - cover.stop: cover_14

  - platform: gpio
    name: 'Kuchnia_DU'
    id: in_29
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 0
      mode:
        input: true
    #   inverted: true
    # on_press:
    #   then:
    #     - cover.open: cover_15
    # on_release:
    #   then:
    #     - cover.stop: cover_15

  - platform: gpio
    name: 'Kuchnia_DS'
    id: in_30
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 1
      mode:
        input: true
    #   inverted: true
    # on_press:
    #   then:
    #     - cover.close: cover_15
    # on_release:
    #   then:
    #     - cover.stop: cover_15

  - platform: gpio
    name: 'Kuchnia_OU'
    id: in_31
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 2
      mode:
        input: true
      # inverted: true
    # on_press:
    #   then:
    #     - cover.open: cover_16
    # on_release:
    #   then:
    #     - cover.stop: cover_16

  - platform: gpio
    name: 'Łazienka_OS'
    id: in_32
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 3
      mode:
        input: true
      # inverted: true
    # on_press:
    #   then:
    #     - cover.close: cover_16
    # on_release:
    #   then:
    #     - cover.stop: cover_16

  - platform: gpio
    name: 'Łazienka_OU'
    id: in_33
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 4
      mode:
        input: true
      # inverted: true

  - platform: gpio
    name: 'Drzwi_Wejściowe'
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 5
      mode:
        input: true
      # inverted: true

  - platform: gpio
    name: 'Gabinet_OU'
    id: in_35
    pin:
      pcf8574: pcf_inputs_28to35_menu
      number: 6
      mode:
        input: true
      # inverted: true
